sudo: false
language: perl
perl:
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - cpanm --quiet --notest --skip-satisfied Pod::Weaver::Section::Contributors
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
